tap 'earthly/earthly' || true
tap 'heroku/brew' || true
tap 'planetscale/tap' || true

brew 'awscli'
brew 'earthly'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'heroku'
brew 'n'
brew 'neofetch'
brew 'pinentry-mac'
brew 'postgresql@15'
brew 'pscale'
brew 'pnpm'
brew 'poetry'
brew 'pure'
brew 'pyenv'
brew 'zsh'
brew 'zsh-syntax-highlighting'

cask '1password'
cask '1password-cli'
cask 'backblaze'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'gpg-suite-no-mail'
cask 'iterm2'
cask 'keybase'
cask 'little-snitch'
cask 'notion'
cask 'parallels'
cask 'postman'
cask 'raycast'
cask 'setapp'
cask 'slack'
cask 'steam'
cask 'visual-studio-code'
cask 'zoom'